In [1]:
import pdfplumber, re
import pandas as pd
from transformers import pipeline
import geemap
import folium

In [2]:
clf = pipeline("text-classification", model="climatebert/environmental-claims")
specificity_clf = pipeline("text-classification", model="climatebert/distilroberta-base-climate-specificity")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

In [3]:
def extract_claims(pdf_path, company_name):
    text = ""
    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            text += (page.extract_text() or "") + " "

    sentences = re.split(r'(?<=[.!?])\s+', text)
    sentences = [s.strip() for s in sentences if len(s.strip()) > 20]

    claims = []
    for s in sentences:
        result = clf(s, truncation=True, max_length=512)[0]
        if result["label"] == "yes":
            claims.append(s)

    df = pd.DataFrame({"company": company_name, "claim": claims})
    df.to_csv(f"data/claims/{company_name}_claims.csv", index=False)
    print(f"{company_name}: {len(sentences)} sentences, {len(claims)} claims")
    return df

In [4]:
# Change these two lines only when switching to a new company/report
pdf_path = "Reports/sdguthrie.pdf"
company_name = "sdguthrie"

In [5]:
sdg_df = extract_claims(pdf_path, company_name)
sdg_df

sdguthrie: 882 sentences, 122 claims

       company                                              claim
0    sdguthrie  By harnessing the power of innovation,\nwe unl...
1    sdguthrie  Our vision of a “Beyond Zero” future inspires ...
2    sdguthrie  Launched in 2024, our “Beyond Zero” developmen...
3    sdguthrie  Solomon Islands, with 35,799 benefitting from ...
4    sdguthrie  GOING BEYOND\nAs we scale our business and sus...
..         ...                                                ...
117  sdguthrie  NBPOL also supported\nIndonesia’s palm oil ind...
118  sdguthrie  MOVING FORWARD\nIndonesia\nProgramme Number of...
119  sdguthrie  By prioritising customer privacy, data protect...
120  sdguthrie  upholding the highest ethical standards across...
121  sdguthrie  We will\nalso continue to strengthen anti-corr...

[122 rows x 2 columns]

In [6]:
def tag_claim(text):
    t = text.lower()
    specificity_result = specificity_clf(text, truncation=True, max_length=512)[0]
    return {
        "claim": text,
        "deforestation": "deforestation" in t,
        "traceability": "traceab" in t or "traceable" in t,
        "ndpe": "ndpe" in t or "no deforestation" in t,
        "peat": "peat" in t,
        "deadline": next((y for y in ["2025","2030","2050","2013"] if y in t), None),
        "strength": "hard" if ("no deforestation" in t or "deforestation-free" in t or "zero" in t) else "soft",
        "specificity": specificity_result["label"],
        "specificity_score": specificity_result["score"],
    }

tagged = pd.DataFrame([tag_claim(c) for c in sdg_df ["claim"]])
tagged.to_csv(f"data/claims/{company_name}_tagged.csv", index=False)
tagged

,claim,deforestation,traceability,ndpe,peat,deadline,strength,specificity,specificity_score
0,"By harnessing the power of innovation,\nwe unl...",False,False,False,False,NaN,soft,non,0.781647
1,Our vision of a “Beyond Zero” future inspires ...,False,False,False,False,NaN,hard,non,0.850353
2,"Launched in 2024, our “Beyond Zero” developmen...",False,False,False,False,NaN,hard,non,0.608760
3,"Solomon Islands, with 35,799 benefitting from ...",False,False,False,False,NaN,soft,spec,0.802242
4,GOING BEYOND\nAs we scale our business and sus...,False,False,False,False,NaN,hard,spec,0.779192
...,...,...,...,...,...,...,...,...,...
117,NBPOL also supported\nIndonesia’s palm oil ind...,False,False,False,False,NaN,soft,spec,0.614121
118,MOVING FORWARD\nIndonesia\nProgramme Number of...,False,False,False,False,NaN,hard,spec,0.705242
119,"By prioritising customer privacy, data protect...",False,False,False,False,NaN,soft,non,0.913277
120,upholding the highest ethical standards across...,False,False,False,False,NaN,soft,non,0.793104
121,We will\nalso continue to strengthen anti-corr...,False,False,False,False,NaN,soft,non,0.855503

In [7]:
specific_claims = tagged[tagged["specificity"] == "spec"].reset_index(drop=True)
specific_claims.to_csv(f"data/claims/{company_name}_specific_claims.csv", index=False)
print(f"{len(specific_claims)} of {len(tagged)} claims are specific (checkable)")
specific_claims

50 of 122 claims are specific (checkable)

,claim,deforestation,traceability,ndpe,peat,deadline,strength,specificity,specificity_score
0,"Solomon Islands, with 35,799 benefitting from ...",False,False,False,False,NaN,soft,spec,0.802242
1,GOING BEYOND\nAs we scale our business and sus...,False,False,False,False,NaN,hard,spec,0.779192
2,Leveraging our supply chain in Papua New Guine...,False,False,False,False,2030,soft,spec,0.893180
3,We are developing a regenerative agricultural\...,False,False,False,False,NaN,soft,spec,0.874616
4,Transforming Lives Through • Community Rights ...,True,True,False,False,NaN,hard,spec,0.671456
5,through capacity building and\nTackling Waste ...,False,False,False,False,NaN,soft,spec,0.552657
6,"Restore, rehabilitate or conserve – Reforestat...",False,False,False,False,2030,hard,spec,0.709963
7,100% 100%\nAchieved Achieved Became the\nMalay...,False,False,False,False,NaN,hard,spec,0.802048
8,We are guided by approved by SBTi\nZero 2030 t...,False,False,False,False,2030,hard,spec,0.665755
9,Achieved for greenhouse gas\ntraceability to m...,True,True,True,True,NaN,hard,spec,0.831286
10,Harvested the very first towards accelerated (...,False,False,False,False,NaN,soft,spec,0.622183
11,"We extend our efforts beyond our operations, a...",False,False,False,True,2030,soft,spec,0.669504
12,low-carbon palm oil solutions.,False,False,False,False,NaN,soft,spec,0.517231
13,"Ongoing key\n40,250 metric tonnes (MT) of\nini...",False,False,False,False,NaN,hard,spec,0.753834
14,Over 70% of our refineries now produce oils wi...,False,False,False,False,NaN,soft,spec,0.779258
15,With 67% of our net emissions reduced our Scop...,False,False,True,True,NaN,soft,spec,0.892418
16,"Additionally, we lowered our\nScope 1 Energy a...",False,False,False,False,NaN,soft,spec,0.964027
17,• Enhancing Scope 3 emission reductions throug...,False,False,False,False,NaN,soft,spec,0.784957
18,GHG Emissions Intensities Unit FY2023 FY2024 S...,False,False,False,False,NaN,hard,spec,0.595611
19,and compliance with our deforestation-free com...,True,False,False,False,NaN,hard,spec,0.512257
20,significant milestone by delivering its first ...,True,False,True,False,NaN,hard,spec,0.962195
21,"of 24,250 MT arrived at SD Guthrie Internation...",True,True,False,False,NaN,hard,spec,0.946000
22,Pioneered by SD Guthrie in 1985 and now an ind...,False,False,False,False,NaN,hard,spec,0.620457
23,Traceability to Plantation\nDeforestation-Free...,True,True,False,False,NaN,hard,spec,0.595711
24,This pilot shipment is fully traceable and ver...,True,True,False,False,NaN,hard,spec,0.587408
25,by enabling traceability of raw materials thro...,True,True,True,True,NaN,hard,spec,0.559919
26,"For our upstream mills,\n‘Working with Supplie...",True,False,False,False,NaN,soft,spec,0.566366
27,one facility\nFY2022 FY2023 FY2024 Specific to...,False,False,False,False,NaN,soft,spec,0.826580
28,By capturing and converting methane from palm ...,False,False,False,False,NaN,soft,spec,0.617521
29,This initiative resulted in annual savings of ...,False,False,False,False,NaN,soft,spec,0.732312
30,"Additionally, we utilise mulched empty 22 km o...",False,False,False,False,NaN,soft,spec,0.913451
31,SD Guthrie International Biodiesel launched th...,False,False,False,False,NaN,soft,spec,0.588291
32,We are committed to ensuring that the\n(PKE) i...,False,False,False,False,NaN,soft,spec,0.506490
33,We have installed rainwater harvesting systems...,False,False,False,False,NaN,soft,spec,0.722157
34,"Our sustainability initiatives\n94,572 94,420 ...",False,False,False,False,NaN,soft,spec,0.572407
35,We expanded reforestation efforts during the y...,False,False,False,False,NaN,soft,spec,0.694620
36,"Building on our Biodiversity Policy, we are wo...",False,False,False,False,2025,hard,spec,0.663358
37,"Running from 2023 to 2025, the project aims to...",False,False,False,True,2025,soft,spec,0.576873
38,Geotagging\nThe project will evaluate best man...,False,False,False,True,NaN,soft,spec,0.515576
39,"in 2022, 26 estates have participated, with 23...",False,False,False,False,NaN,soft,spec,0.726903
40,We also advanced our efforts to convert rubber...,False,False,False,False,NaN,soft,spec,0.729527
41,"By the end of 2024, we successfully planted 13...",False,False,False,False,NaN,soft,spec,0.938347
42,"Additionally, our\nregenerative agriculture fr...",False,False,False,False,NaN,soft,spec,0.627465
43,The tree nurseries that were March 2023 to res...,False,False,False,True,NaN,hard,spec,0.896737
44,"By December 2024, we had completed\nused water...",False,False,False,False,NaN,soft,spec,0.953082
45,We aim to realise a 20% increase in\n(OHD) cer...,False,False,False,False,NaN,soft,spec,0.867749
46,As part of our commitment issues related to la...,False,True,False,False,NaN,soft,spec,0.599000
47,"Additionally, initiatives like the\nMama Loose...",False,False,False,False,NaN,soft,spec,0.873915
48,NBPOL also supported\nIndonesia’s palm oil ind...,False,False,False,False,NaN,soft,spec,0.614121
49,MOVING FORWARD\nIndonesia\nProgramme Number of...,False,False,False,False,NaN,hard,spec,0.705242

In [8]:
gar_final = tagged[
    (tagged["specificity"] == "spec") &
    (tagged["deforestation"] | tagged["ndpe"] | tagged["peat"] | tagged["traceability"])
]
gar_final.to_csv(f"data/claims/{company_name}_final_claims.csv", index=False)
gar_final

,claim,deforestation,traceability,ndpe,peat,deadline,strength,specificity,specificity_score
9,Transforming Lives Through • Community Rights ...,True,True,False,False,NaN,hard,spec,0.671456
18,Achieved for greenhouse gas\ntraceability to m...,True,True,True,True,NaN,hard,spec,0.831286
23,"We extend our efforts beyond our operations, a...",False,False,False,True,2030,soft,spec,0.669504
45,With 67% of our net emissions reduced our Scop...,False,False,True,True,NaN,soft,spec,0.892418
49,and compliance with our deforestation-free com...,True,False,False,False,NaN,hard,spec,0.512257
53,significant milestone by delivering its first ...,True,False,True,False,NaN,hard,spec,0.962195
54,"of 24,250 MT arrived at SD Guthrie Internation...",True,True,False,False,NaN,hard,spec,0.946000
65,Traceability to Plantation\nDeforestation-Free...,True,True,False,False,NaN,hard,spec,0.595711
67,This pilot shipment is fully traceable and ver...,True,True,False,False,NaN,hard,spec,0.587408
69,by enabling traceability of raw materials thro...,True,True,True,True,NaN,hard,spec,0.559919
73,"For our upstream mills,\n‘Working with Supplie...",True,False,False,False,NaN,soft,spec,0.566366
99,"Running from 2023 to 2025, the project aims to...",False,False,False,True,2025,soft,spec,0.576873
100,Geotagging\nThe project will evaluate best man...,False,False,False,True,NaN,soft,spec,0.515576
106,The tree nurseries that were March 2023 to res...,False,False,False,True,NaN,hard,spec,0.896737
113,As part of our commitment issues related to la...,False,True,False,False,NaN,soft,spec,0.599000

In [9]:
uml_path = "UML-Jan-2026.csv"
uml = pd.read_csv(uml_path, sep=";", encoding="latin1")
uml.columns = [" ".join(str(column).replace("﻿", "").split()) for column in uml.columns]

group_col = next((column for column in uml.columns if column.casefold() == "group name"), None)
if group_col is None:
    raise KeyError(f"'Group Name' column not found. Loaded columns: {list(uml.columns)}")

sdg_mills = uml[
    uml[group_col].str.contains("SIME DARBY", case=False, na=False, regex=False)
].reset_index(drop=True)

print("SD Guthrie mills:", len(sdg_mills))
sdg_mills

SD Guthrie mills: 2

,UML ID,Group Name,Parent Company,Mill Name,RSPO Status,RSPO type,Date RSPO Certification Status,Latitude,Longitude,GPS coordinates,ISO,Country,Province,District,Confidence level,Alternative name
0,PO1000010727,SIME DARBY PLANTATION BHD,MARKHAM FARMING COMPANY LTD,ERAP / MARKHAM FAMRING,RSPO Certified,"RSPO Certified, IP, MB",13/01/2026,-658.087,14.664.222,"-6.58087, 146.64222",PNG,Papua New Guinea,Morobe,Chivasing,2-High Confidence,NaN
1,PO1000011310,SIME DARBY,PT PADANG PALMA PERMAI,TAMIANG POM,Not RSPO Certified,NaN,13/01/2026,430.555,980.267,"4.30555, 98.0267",IDN,Indonesia,Aceh,Aceh Tamiang,2-High Confidence,NaN

In [10]:
for name in ["SIME DARBY", "GUTHRIE", "SD GUTHRIE", "SIME"]:
    n = uml[group_col].str.contains(name, case=False, na=False, regex=False).sum()
    print(f"'{name}': {n} in Group Name")
    # Parent Company માં પણ જુઓ
    pc = uml["Parent Company"].str.contains(name, case=False, na=False, regex=False).sum()
    print(f"'{name}': {pc} in Parent Company")

'SIME DARBY': 2 in Group Name
'SIME DARBY': 39 in Parent Company
'GUTHRIE': 0 in Group Name
'GUTHRIE': 1 in Parent Company
'SD GUTHRIE': 0 in Group Name
'SD GUTHRIE': 0 in Parent Company
'SIME': 66 in Group Name
'SIME': 40 in Parent Company

In [11]:
# "Latitude"/"Longitude" columns are corrupted (extra thousand-separator dots),
# so parse the clean "lat, lon" pairs out of "GPS coordinates" instead.
_coords = sdg_mills["GPS coordinates"].str.split(",", expand=True)

mill_coords = sdg_mills[[group_col, "Mill Name"]].copy()
mill_coords["latitude"] = pd.to_numeric(_coords[0].str.strip(), errors="coerce")
mill_coords["longitude"] = pd.to_numeric(_coords[1].str.strip(), errors="coerce")
mill_coords = mill_coords.dropna(subset=["latitude", "longitude"]).reset_index(drop=True)

mill_coords

                  Group Name                Mill Name  latitude  longitude
0  SIME DARBY PLANTATION BHD  ERAP / MARKHAM FAMRING   -6.58087  146.64222
1                 SIME DARBY              TAMIANG POM   4.30555   98.02670

In [12]:
import ee
ee.Authenticate()

True

In [13]:
ee.Initialize(project='thesis-greenwashing')
print("Connected!")

Connected!

---
# Layer 2a — Multi-company forest loss
Reusable function computing forest cover, total loss, and post-2020 loss in a single Earth Engine call per mill (Hansen v1.13, 2000-2025). Works for any company via keyword match against the UML group name.

In [14]:
# Reusable mill extractor — searches BOTH Group Name and Parent Company.
# Many companies (e.g. SD Guthrie / SIME DARBY) have their mills listed under
# Parent Company, not Group Name — searching only one column undercounts them.
# Coordinates are parsed from "GPS coordinates" because the Latitude/Longitude
# columns in the UML are corrupted (thousand-separator dots).

def get_company_mills(uml_df, keyword, company_name):
    mask = (
        uml_df[group_col].str.contains(keyword, case=False, na=False, regex=True)
        | uml_df["Parent Company"].str.contains(keyword, case=False, na=False, regex=True)
    )
    mills = uml_df[mask].drop_duplicates(subset=["Mill Name", "GPS coordinates"]).reset_index(drop=True)

    coords = mills["GPS coordinates"].str.split(",", expand=True)

    out = mills[[group_col, "Mill Name", "Country"]].copy()
    out["company"] = company_name
    out["latitude"] = pd.to_numeric(coords[0].str.strip(), errors="coerce")
    out["longitude"] = pd.to_numeric(coords[1].str.strip(), errors="coerce")
    out = out.dropna(subset=["latitude", "longitude"]).reset_index(drop=True)

    print(f"{company_name}: {len(out)} mills with valid coordinates")
    return out

In [15]:
# One Earth Engine call per mill — returns forest 2000, total loss, post-2020 loss
# Uses Hansen v1.13 (2000-2025) throughout. lossyear >= 21 means 2021 onwards = EUDR window.

hansen = ee.Image("UMD/hansen/global_forest_change_2025_v1_13")
pixel_ha = ee.Image.pixelArea().divide(10000)

_bands = (
    hansen.select("treecover2000").gt(30).multiply(pixel_ha).rename("forest_2000_ha")
    .addBands(hansen.select("lossyear").gt(0).multiply(pixel_ha).rename("loss_total_ha"))
    .addBands(hansen.select("lossyear").gte(21).multiply(pixel_ha).rename("loss_post2020_ha"))
)

def mill_forest_loss(lon, lat, buffer_m=10000):
    region = ee.Geometry.Point([lon, lat]).buffer(buffer_m)
    stats = _bands.reduceRegion(
        reducer=ee.Reducer.sum(),
        geometry=region,
        scale=30,
        maxPixels=1e10,
    ).getInfo()
    return (
        stats.get("forest_2000_ha") or 0,
        stats.get("loss_total_ha") or 0,
        stats.get("loss_post2020_ha") or 0,
    )

In [16]:
import time
def company_forest_loss(uml_df, keyword, company_name, buffer_m=10000):
    mills = get_company_mills(uml_df, keyword, company_name)
    rows = []
    for i, (_, m) in enumerate(mills.iterrows(), 1):
        try:
            f, lt, lp = mill_forest_loss(m["longitude"], m["latitude"], buffer_m)
            rows.append({
                "company": company_name,
                "mill_name": m["Mill Name"],
                "country": m["Country"],
                "latitude": m["latitude"],
                "longitude": m["longitude"],
                "forest_2000_ha": f,
                "loss_total_ha": lt,
                "loss_post2020_ha": lp,
            })
            print(f"  [{i}/{len(mills)}] {m['Mill Name']}: {lp:,.0f} ha post-2020")
        except Exception as exc:
            print(f"  [{i}/{len(mills)}] FAILED {m['Mill Name']}: {exc}")
        time.sleep(0.2)
    df = pd.DataFrame(rows)
    df.to_csv(f"data/mills/{company_name}_mills.csv", index=False)
    return df

## Verification step

Run Wilmar first and check the total against the figure already on record.
If it reproduces, the results are yours and defensible. If it does not,
find out why now — not in the viva.

This may take 5-15 minutes depending on how many mills Wilmar has.
Progress prints after each mill.

In [17]:
wilmar_mills = company_forest_loss(uml, "WILMAR", "wilmar")

print("\n=== WILMAR TOTAL ===")
print(f"Mills processed: {len(wilmar_mills)}")
print(f"Forest 2000:     {wilmar_mills['forest_2000_ha'].sum():,.0f} ha")
print(f"Loss total:      {wilmar_mills['loss_total_ha'].sum():,.0f} ha")
print(f"Loss post-2020:  {wilmar_mills['loss_post2020_ha'].sum():,.0f} ha")

wilmar: 45 mills with valid coordinates
  [1/45] SABAHMAS: 6,675 ha post-2020
  [2/45] SAREMAS 1: 3,219 ha post-2020
  [3/45] SAREMAS 2: 4,849 ha post-2020
  [4/45] TERUSAN: 1,352 ha post-2020
  [5/45] SAPI: 2,049 ha post-2020
  [6/45] REKA HALUS: 2,394 ha post-2020
  [7/45] MUSTIKA SEMBULUH 1: 2,237 ha post-2020
  [8/45] KERRY SAWIT INDONESIA 1: 511 ha post-2020
  [9/45] RIBUBONUS: 1,309 ha post-2020
  [10/45] SRI KAMUSAN: 3,019 ha post-2020
  [11/45] PINANG AWAM: 3,978 ha post-2020
  [12/45] KENCANA SAWIT INDONESIA: 9,097 ha post-2020
  [13/45] BURNAI TIMUR: 2,829 ha post-2020
  [14/45] SARANA TITIAN PERMATA PKS 1: 497 ha post-2020
  [15/45] AMP PLANTATION: 1,720 ha post-2020
  [16/45] DABUK REJO: 3,856 ha post-2020
  [17/45] BUMI SAWIT KENCANA: 1,023 ha post-2020
  [18/45] BENSO OIL PALM PLANTATION OIL MILL: 4,057 ha post-2020
  [19/45] DAYA LABUHAN INDAH 2: 3,267 ha post-2020
  [20/45] GERSINDO MINANG PLANTATION: 2,994 ha post-2020
  [21/45] MENTAYA SAWIT MAS: 1,237 ha post-2020
  [22/45] RIMBA HARAPAN SAKTI: 495 ha post-2020
  [23/45] SUBURMAS: 5,803 ha post-2020
  [24/45] KARUNIA KENCANA PERMAI SEJATI: 1,123 ha post-2020
  [25/45] SELABU: 4,077 ha post-2020
  [26/45] AGROINDO INDAH PERSADA 1: 1,993 ha post-2020
  [27/45] BUMI PRATAMA KHATULISTIWA: 2,120 ha post-2020
  [28/45] SINAR SIAK DIAN PERMAI: 6,878 ha post-2020
  [29/45] SIAK PRIMA SAKTI: 2,798 ha post-2020
  [30/45] MURINI SAM-SAM PELINTUNG: 767 ha post-2020
  [31/45] AGRONUSA INVESTAMA 2 - PAHAUMAN: 2,956 ha post-2020
  [32/45] SINAR PERDANA CARAKA: 2,041 ha post-2020
  [33/45] BULUH CINA: 2,499 ha post-2020
  [34/45] AEK BATU: 2,564 ha post-2020
  [35/45] AGROINDO INDAH PERSADA 2: 6,543 ha post-2020
  [36/45] AGROINDO INDAH PERSADA 3: 3,729 ha post-2020
  [37/45] MURINI SAM-SAM KANDIS: 1,465 ha post-2020
  [38/45] KERRY SAWIT INDONESIA 2: 719 ha post-2020
  [39/45] AGRO PALINDO SAKTI 2: 4,010 ha post-2020
  [40/45] MUSTIKA SEMBULUH 2: 1,440 ha post-2020
  [41/45] DAYA LABUHAN INDAH I: 2,287 ha post-2020
  [42/45] SARANA TITIAN PERMATA PKS 2: 934 ha post-2020
  [43/45] AGRONUSA INVESTAMA 3 - SAMBAS: 2,724 ha post-2020
  [44/45] CALARO: 1,617 ha post-2020
  [45/45] EYOP INDUSTRIES LTD: 3,855 ha post-2020

=== WILMAR TOTAL ===
Mills processed: 45
Forest 2000:     1,119,815 ha
Loss total:      711,441 ha
Loss post-2020:  127,606 ha

## Run all companies

Only run this once Wilmar has verified. Keyword patterns include former
names and parent groups — SD Guthrie is listed as SIME DARBY in the UML.

Check the mill counts printed for each company. If any company returns
0 mills, its keyword needs adjusting before you trust the master table.

In [18]:
COMPANIES = {
    "wilmar":          "WILMAR",
    "gar":             "GOLDEN AGRI|SINAR MAS",
    "sdguthrie":       "SIME DARBY|GUTHRIE",
    "musimmas":        "MUSIM MAS",
    "ioi":             "IOI CORPORATION|IOI GROUP",
    "klk":             "KUALA LUMPUR KEPONG|KLK",
    "bumitama":        "BUMITAMA",
    "astraagro":       "ASTRA AGRO|ASTRA",
    "genting":         "GENTING",
    "sipef":           "SIPEF",
    "firstresources":  "FIRST RESOURCES",
}
all_mills = []
for _name, _keyword in COMPANIES.items():
    print(f"\n=== {_name.upper()} ===")
    all_mills.append(company_forest_loss(uml, _keyword, _name))
mills_master = pd.concat(all_mills, ignore_index=True)
mills_master.to_csv("data/mills/all_mills_forest_loss.csv", index=False)
print(f"\nSaved {len(mills_master)} mills across {len(COMPANIES)} companies")

=== WILMAR ===
wilmar: 45 mills with valid coordinates
  [1/45] SABAHMAS: 6,675 ha post-2020
  [2/45] SAREMAS 1: 3,219 ha post-2020
  [3/45] SAREMAS 2: 4,849 ha post-2020
  [4/45] TERUSAN: 1,352 ha post-2020
  [5/45] SAPI: 2,049 ha post-2020
  [6/45] REKA HALUS: 2,394 ha post-2020
  [7/45] MUSTIKA SEMBULUH 1: 2,237 ha post-2020
  [8/45] KERRY SAWIT INDONESIA 1: 511 ha post-2020
  [9/45] RIBUBONUS: 1,309 ha post-2020
  [10/45] SRI KAMUSAN: 3,019 ha post-2020
  [11/45] PINANG AWAM: 3,978 ha post-2020
  [12/45] KENCANA SAWIT INDONESIA: 9,097 ha post-2020
  [13/45] BURNAI TIMUR: 2,829 ha post-2020
  [14/45] SARANA TITIAN PERMATA PKS 1: 497 ha post-2020
  [15/45] AMP PLANTATION: 1,720 ha post-2020
  [16/45] DABUK REJO: 3,856 ha post-2020
  [17/45] BUMI SAWIT KENCANA: 1,023 ha post-2020
  [18/45] BENSO OIL PALM PLANTATION OIL MILL: 4,057 ha post-2020
  [19/45] DAYA LABUHAN INDAH 2: 3,267 ha post-2020
  [20/45] GERSINDO MINANG PLANTATION: 2,994 ha post-2020
  [21/45] MENTAYA SAWIT MAS: 1,237 ha post-2020
  [22/45] RIMBA HARAPAN SAKTI: 495 ha post-2020
  [23/45] SUBURMAS: 5,803 ha post-2020
  [24/45] KARUNIA KENCANA PERMAI SEJATI: 1,123 ha post-2020
  [25/45] SELABU: 4,077 ha post-2020
  [26/45] AGROINDO INDAH PERSADA 1: 1,993 ha post-2020
  [27/45] BUMI PRATAMA KHATULISTIWA: 2,120 ha post-2020
  [28/45] SINAR SIAK DIAN PERMAI: 6,878 ha post-2020
  [29/45] SIAK PRIMA SAKTI: 2,798 ha post-2020
  [30/45] MURINI SAM-SAM PELINTUNG: 767 ha post-2020
  [31/45] AGRONUSA INVESTAMA 2 - PAHAUMAN: 2,956 ha post-2020
  [32/45] SINAR PERDANA CARAKA: 2,041 ha post-2020
  [33/45] BULUH CINA: 2,499 ha post-2020
  [34/45] AEK BATU: 2,564 ha post-2020
  [35/45] AGROINDO INDAH PERSADA 2: 6,543 ha post-2020
  [36/45] AGROINDO INDAH PERSADA 3: 3,729 ha post-2020
  [37/45] MURINI SAM-SAM KANDIS: 1,465 ha post-2020
  [38/45] KERRY SAWIT INDONESIA 2: 719 ha post-2020
  [39/45] AGRO PALINDO SAKTI 2: 4,010 ha post-2020
  [40/45] MUSTIKA SEMBULUH 2: 1,440 ha post-2020
  [41/45] DAYA LABUHAN INDAH I: 2,287 ha post-2020
  [42/45] SARANA TITIAN PERMATA PKS 2: 934 ha post-2020
  [43/45] AGRONUSA INVESTAMA 3 - SAMBAS: 2,724 ha post-2020
  [44/45] CALARO: 1,617 ha post-2020
  [45/45] EYOP INDUSTRIES LTD: 3,855 ha post-2020

=== GAR ===
gar: 50 mills with valid coordinates
  [1/50] UJUNG TANJUNG: 1,693 ha post-2020
  [2/50] LIBO: 1,029 ha post-2020
  [3/50] SAM-SAM: 1,683 ha post-2020
  [4/50] SEKIJANG: 6,399 ha post-2020
  [5/50] NAGA SAKTI: 10,197 ha post-2020
  [6/50] RAMARAMA: 3,303 ha post-2020
  [7/50] BUMI PALMA: 1,921 ha post-2020
  [8/50] INDRA SAKTI: 3,747 ha post-2020
  [9/50] PADANG HALABAN: 3,495 ha post-2020
  [10/50] LANGGA PAYUNG PALM OIL MILL: 2,310 ha post-2020
  [11/50] BATU AMPAR: 5,474 ha post-2020
  [12/50] TANAH LAUR: 5,015 ha post-2020
  [13/50] HANAU: 5,149 ha post-2020
  [14/50] SUNGAI RUNGAU: 4,296 ha post-2020
  [15/50] SEMILAR: 1,603 ha post-2020
  [16/50] SUNGAI BUAYA: 5,062 ha post-2020
  [17/50] SUNGAI MERAH: 4,219 ha post-2020
  [18/50] JELATANG: 4,191 ha post-2020
  [19/50] LANGLING: 4,592 ha post-2020
  [20/50] MASKAPAI PERKEBUAN LEIDONG WEST: 9,087 ha post-2020
  [21/50] TANJUNG KEMBIRI: 1,021 ha post-2020
  [22/50] BUMI SAWIT: 3,996 ha post-2020
  [23/50] PANGKALAN PANJI: 2,000 ha post-2020
  [24/50] MUARA KANDIS: 5,575 ha post-2020
  [25/50] PEKAWAI: 906 ha post-2020
  [26/50] KENANGA PALM OIL MILL: 1,808 ha post-2020
  [27/50] SUNGAI BENGKAL: 3,707 ha post-2020
  [28/50] BUKIT PERAK: 7,426 ha post-2020
  [29/50] MUARA WAHAU: 3,986 ha post-2020
  [30/50] JAK LUAY: 1,678 ha post-2020
  [31/50] PT BINASAWIT ABADI PRATAMA - PERDANA MILL: 1,191 ha post-2020
  [32/50] BATU KAPUR: 4,964 ha post-2020
  [33/50] BELIAN: 603 ha post-2020
  [34/50] PERSADA GRAHA MANDIRI: 974 ha post-2020
  [35/50] SUNGAI KIKIM: 3,950 ha post-2020
  [36/50] PELAKAR: 7,438 ha post-2020
  [37/50] SENAKIN: 1,377 ha post-2020
  [38/50] SUNGAI KUPANG: 4,912 ha post-2020
  [39/50] KUAYAN: 938 ha post-2020
  [40/50] TANGAR: 2,640 ha post-2020
  [41/50] KAPUASINDO PALM INDUSTRY: 1,258 ha post-2020
  [42/50] KASUARI: 4,820 ha post-2020
  [43/50] SUNGAI MAGALAU: 1,810 ha post-2020
  [44/50] JALEMO: 1,733 ha post-2020
  [45/50] SAWITA: 3,599 ha post-2020
  [46/50] SAKO: 1,604 ha post-2020
  [47/50] SUNGAI AIR JERNIH: 3,122 ha post-2020
  [48/50] RANTAU PANJANG: 1,201 ha post-2020
  [49/50] GUNUNG KOMBENG: 3,881 ha post-2020
  [50/50] BANGUNG NUSA MANDIRI KENARI: 2,652 ha post-2020

=== SDGUTHRIE ===
sdguthrie: 42 mills with valid coordinates
  [1/42] BINUANG (SOU 28): 3,128 ha post-2020
  [2/42] MEROTAI (SOU 30): 5,343 ha post-2020
  [3/42] SANDAKAN BAY (SOU 26): 3,295 ha post-2020
  [4/42] EAST (SOU 8): 2,021 ha post-2020
  [5/42] TANAH MERAH (SOU 14): 2,614 ha post-2020
  [6/42] SEGALIUD (SOU 25): 3,921 ha post-2020
  [7/42] WEST (SOU 9): 1,769 ha post-2020
  [8/42] SUNGAI DINGIN (SOU 1): 2,961 ha post-2020
  [9/42] YONG PENG (SOU 19A): 4,226 ha post-2020
  [10/42] BUKIT KERAYONG (SOU 7): 2,201 ha post-2020
  [11/42] JABOR (SOU 12): 3,027 ha post-2020
  [12/42] TENNAMARAM (SOU 6): 1,814 ha post-2020
  [13/42] GIRAM (SOU 29): 7,775 ha post-2020
  [14/42] GUNUNG MAS (SOU 21): 5,544 ha post-2020
  [15/42] DIAMOND JUBILEE (SOU 18): 2,997 ha post-2020
  [16/42] NORDANAL (SOU 19): 2,942 ha post-2020
  [17/42] CHAAH (SOU 20): 2,477 ha post-2020
  [18/42] ELPHIL (SOU 3): 3,881 ha post-2020
  [19/42] BUKIT PUTERI (SOU 10): 4,197 ha post-2020
  [20/42] SERI INTAN (SOU 5): 3,527 ha post-2020
  [21/42] BUKIT BENUT (SOU 22): 3,363 ha post-2020
  [22/42] SELABA (SOU 5): 2,584 ha post-2020
  [23/42] FLEMINGTON (SOU 4): 3,404 ha post-2020
  [24/42] KERDAU (SOU 11): 1,648 ha post-2020
  [25/42] KOK FOH (SOU 16): 3,713 ha post-2020
  [26/42] LABU (SOU 13): 2,180 ha post-2020
  [27/42] SUA BETONG (SOU 15): 2,475 ha post-2020
  [28/42] MELALAP (SOU 27): 1,423 ha post-2020
  [29/42] HADAPAN (SOU 24): 3,083 ha post-2020
  [30/42] CHERSONESE (SOU 2): 1,070 ha post-2020
  [31/42] PEKAKA (SOU 34): 5,835 ha post-2020
  [32/42] LAVANG (SOU 31): 4,377 ha post-2020
  [33/42] RAJAWALI (SOU 32): 6,273 ha post-2020
  [34/42] DERAWAN (SOU 33): 6,496 ha post-2020
  [35/42] ULU REMIS (SOU 23): 2,445 ha post-2020
  [36/42] RANTAU PANJANG POM, PT GPI: 4,203 ha post-2020
  [37/42] KEMPAS (SOU 17): 3,360 ha post-2020
  [38/42] PAGOH (SOU 19): 2,553 ha post-2020
  [39/42] SEPANG (SOU 09A): 2,298 ha post-2020
  [40/42] MOSTYN (SOU 30B): 5,149 ha post-2020
  [41/42] ERAP / MARKHAM FAMRING : 1,400 ha post-2020
  [42/42] TAMIANG POM: 3,138 ha post-2020

=== MUSIMMAS ===
musimmas: 18 mills with valid coordinates
  [1/18] BATANG KULIM: 5,998 ha post-2020
  [2/18] AGROWIRATAMA: 4,504 ha post-2020
  [3/18] SUKAJADI SAWIT MEKAR 1: 1,189 ha post-2020
  [4/18] SUKAJADI SAWIT MEKAR 2: 1,116 ha post-2020
  [5/18] MAJU ANEKA SAWIT: 1,192 ha post-2020
  [6/18] BERKAT SAWIT SEJATI: 5,002 ha post-2020
  [7/18] UNGGUL LESTARI: 2,136 ha post-2020
  [8/18] SIRINGO RINGO: 3,553 ha post-2020
  [9/18] GUNTUNG IDAMAN NUSA 1: 2,079 ha post-2020
  [10/18] BAHANA NUSA INTERINDO: 2,305 ha post-2020
  [11/18] GUNTUNG IDAMAN NUSA 2: 4,534 ha post-2020
  [12/18] MULTI PERSADA GATRA MEGAH: 1,177 ha post-2020
  [13/18] SINAR AGRO RAYA: 4,744 ha post-2020
  [14/18] INDOMAKMUR SAWIT BERJAYA: 4,559 ha post-2020
  [15/18] SARANA ESA CITA: 2,115 ha post-2020
  [16/18] GLOBALINDO ALAM PERKASA PALM OIL MILL: 1,138 ha post-2020
  [17/18] PT. LESTARI ABADI PERKASA: 2,824 ha post-2020
  [18/18] AGRO PALINDO SAKTI: 2,894 ha post-2020

=== IOI ===
ioi: 15 mills with valid coordinates
  [1/15] PAMOL SABAH: 2,790 ha post-2020
  [2/15] GOMALI: 4,409 ha post-2020
  [3/15] PAMOL KLUANG: 2,041 ha post-2020
  [4/15] SAKILAN: 4,701 ha post-2020
  [5/15] BATURONG: 3,570 ha post-2020
  [6/15] BUKIT LEELAU: 3,893 ha post-2020
  [7/15] MAYVIN: 6,063 ha post-2020
  [8/15] PUKIN: 782 ha post-2020
  [9/15] SYARIMO: 12,318 ha post-2020
  [10/15] LADANG SABAH: 6,246 ha post-2020
  [11/15] LEEPANG: 9,414 ha post-2020
  [12/15] MORISEM: 7,432 ha post-2020
  [13/15] UNICO: 5,024 ha post-2020
  [14/15] UNICO DESA: 4,511 ha post-2020
  [15/15] SUKSES KARYA SAWIT: 1,192 ha post-2020

=== KLK ===
klk: 30 mills with valid coordinates
  [1/30] KEKAYAAN PALM OIL MILL: 5,236 ha post-2020
  [2/30] BORNION: 6,768 ha post-2020
  [3/30] RIMMER: 5,045 ha post-2020
  [4/30] LUNGMANIS: 5,647 ha post-2020
  [5/30] JERAM PADANG: 2,701 ha post-2020
  [6/30] MANDAU: 1,087 ha post-2020
  [7/30] PINANG: 3,319 ha post-2020
  [8/30] MILL 2: 3,965 ha post-2020
  [9/30] TAPUNG KANAN: 1,668 ha post-2020
  [10/30] TANJONG MALIM: 2,316 ha post-2020
  [11/30] BATU LINTANG: 3,068 ha post-2020
  [12/30] TUAN MEE: 2,454 ha post-2020
  [13/30] CHANGKAT CHERMIN: 4,120 ha post-2020
  [14/30] NILO 1: 3,124 ha post-2020
  [15/30] NILO 2: 1,898 ha post-2020
  [16/30] KUALA PERTANG: 2,584 ha post-2020
  [17/30] STEELINDO WAHANA PERKASA: 4,853 ha post-2020
  [18/30] PALOH KKS: 5,255 ha post-2020
  [19/30] PADANG BRAHRANG: 795 ha post-2020
  [20/30] BERAU: 3,450 ha post-2020
  [21/30] PARIT SEMBADA: 3,598 ha post-2020
  [22/30] JABON: 2,653 ha post-2020
  [23/30] STABAT: 2,154 ha post-2020
  [24/30] KARYA MAKMUR ABADI: 1,266 ha post-2020
  [25/30] SATU SEMBILAN DELAPAN: 2,530 ha post-2020
  [26/30] MULIA AGRO PERMAI: 927 ha post-2020
  [27/30] TANJUNG KELILING PALM OIL MILL: 1,083 ha post-2020
  [28/30] MILL 1: 3,912 ha post-2020
  [29/30] PT KARYA MAKMUR ABADI: 3,194 ha post-2020
  [30/30] PUTRA BONGAN JAYA: 1,539 ha post-2020

=== BUMITAMA ===
bumitama: 14 mills with valid coordinates
  [1/14] PUNDU NABATINDO: 4,590 ha post-2020
  [2/14] GUNUNG MAKMUR: 5,137 ha post-2020
  [3/14] KENDAWANGAN: 1,700 ha post-2020
  [4/14] KOTAWARINGIN: 1,782 ha post-2020
  [5/14] BUKIT TUNGGAL JAYA: 1,397 ha post-2020
  [6/14] SUKADAMAI: 1,390 ha post-2020
  [7/14] PEMBANGUNAN RAYA: 105 ha post-2020
  [8/14] KATARI AGRO: 2,302 ha post-2020
  [9/14] BUKIT MAKMUR: 1,237 ha post-2020
  [10/14] SUNGAI RASAU: 527 ha post-2020
  [11/14] LAMANDAU: 2,142 ha post-2020
  [12/14] SUNGAI CEMPAGA: 2,830 ha post-2020
  [13/14] BUKIT BELABAN JAYA: 2,552 ha post-2020
  [14/14] TONAM RAYA: 2,859 ha post-2020

=== ASTRAAGRO ===
astraagro: 34 mills with valid coordinates
  [1/34] AGRO NUSA ABADI: 2,437 ha post-2020
  [2/34] BORNEO INDAH MARJAYA: 1,043 ha post-2020
  [3/34] LETAWA: 4,406 ha post-2020
  [4/34] PASANGKAYU: 3,385 ha post-2020
  [5/34] SURYARAYA LESTARI 2: 1,209 ha post-2020
  [6/34] GUNUNG SEJAHTERA DUA INDAH: 5,081 ha post-2020
  [7/34] PERKEBUNAN LEMBAH BHAKTI 1: 2,882 ha post-2020
  [8/34] GUNUNG SEJAHTERA PUTI PESONA: 4,178 ha post-2020
  [9/34] GUNUNG SEJAHTERA IBU PERTIWI: 6,806 ha post-2020
  [10/34] SUBUR AGRO MAKMUR: 270 ha post-2020
  [11/34] TUNGGAL PERKASA PLANTATIONS: 3,806 ha post-2020
  [12/34] KIMIA TIRTA UTAMA: 1,913 ha post-2020
  [13/34] SAWIT ASAHAN INDAH: 2,650 ha post-2020
  [14/34] EKA DURA INDONESIA: 2,524 ha post-2020
  [15/34] WARU KALTIM PLANTATION: 1,814 ha post-2020
  [16/34] SURYARAYA LESTARI 1: 1,641 ha post-2020
  [17/34] SARI ADITYA LOKA 1: 5,623 ha post-2020
  [18/34] ASTRA AGRO LESTARI 1: 2,592 ha post-2020
  [19/34] KARYA TANAH SUBUR: 2,067 ha post-2020
  [20/34] SUMBER KHARISMA PERSADA: 443 ha post-2020
  [21/34] NIRMALA AGRO LESTARI: 1,993 ha post-2020
  [22/34] SARI LEMBAH SUBUR 1: 4,209 ha post-2020
  [23/34] SURYA INDAH NUSANTARA PAGI: 1,250 ha post-2020
  [24/34] SUKSES TANI SUBUR: 2,950 ha post-2020
  [25/34] SARI LEMBAH SUBUR 2: 2,904 ha post-2020
  [26/34] LESTARI TANI TELADAN: 3,769 ha post-2020
  [27/34] KARYANUSA EKA DAYA 1: 781 ha post-2020
  [28/34] SARI ADITYA LOKA 2: 3,771 ha post-2020
  [29/34] PERKEBUNAN LEMBAH BHAKTI 2: 1,856 ha post-2020
  [30/34] LARAS ASTRA KARTIKA: 1,777 ha post-2020
  [31/34] KARYANUSA EKA DAYA 2: 865 ha post-2020
  [32/34] CAKUNG PERMATA NUSA: 1,322 ha post-2020
  [33/34] SAWIT JAYA ABADI: 2,259 ha post-2020
  [34/34] TRIBUANA MAS: 719 ha post-2020

=== GENTING ===
genting: 15 mills with valid coordinates
  [1/15] GENTING AYER ITEM: 2,749 ha post-2020
  [2/15] GENTING INDAH: 1,432 ha post-2020
  [3/15] GENTING JAMBONGAN: 1,004 ha post-2020
  [4/15] GENTING MEWAH: 6,303 ha post-2020
  [5/15] MULIA: 3,118 ha post-2020
  [6/15] GENTING SABAPALM: 3,143 ha post-2020
  [7/15] GENTING TANJUNG: 10,179 ha post-2020
  [8/15] DWIE WARNA KARYA: 983 ha post-2020
  [9/15] GENTING TRUSHIDUP: 5,129 ha post-2020
  [10/15] KHARISMA INTI USAHA: 567 ha post-2020
  [11/15] ASIATIC SABAPALM: 1,339 ha post-2020
  [12/15] SEPANJANG INTI SURYA UTAMA 2: 2,147 ha post-2020
  [13/15] GLOBALINDO AGUNG LESTARI: 1,993 ha post-2020
  [14/15] AGRO ABADI CEMERLANG : 2,968 ha post-2020
  [15/15] KAPUAS MAJU JAYA/GEMILANG OIL MILL: 1,309 ha post-2020

=== SIPEF ===
sipef: 11 mills with valid coordinates
  [1/11] HARGY MILL: 916 ha post-2020
  [2/11] BUKIT MARADJA: 2,549 ha post-2020
  [3/11] PERLABIAN: 3,004 ha post-2020
  [4/11] NAVO MILL: 2,944 ha post-2020
  [5/11] MUKOMUKO POM: 1,814 ha post-2020
  [6/11] BUNGA TANJUNG: 2,323 ha post-2020
  [7/11] BAREMA PALM OIL MILL: 1,337 ha post-2020
  [8/11] UMBUL MAS WISESA: 1,363 ha post-2020
  [9/11] SOUBRE: 2,208 ha post-2020
  [10/11] DENDYMARKER: 6,393 ha post-2020
  [11/11] BOLO: 2,488 ha post-2020

=== FIRSTRESOURCES ===
firstresources: 16 mills with valid coordinates
  [1/16] ARINDO TRI SEJAHTERA: 2,087 ha post-2020
  [2/16] MERIDAN SEJATI SURYA PLANTATION: 6,883 ha post-2020
  [3/16] CILIANDRA PERKASA: 6,231 ha post-2020
  [4/16] SURYA INTISARI RAYA: 3,117 ha post-2020
  [5/16] PT SUBUR ARUMMAKMUR: 1,959 ha post-2020
  [6/16] PERDANA INTI SAWIT PERKASA 1: 3,917 ha post-2020
  [7/16] MURINI WOOD INDAH INDUSTRI: 2,867 ha post-2020
  [8/16] SWADAYA MUKTI PRAKARSA: 1,614 ha post-2020
  [9/16] MERIDAN SEJATI SURYA PLANTATION BANGSAL ACEH: 1,347 ha post-2020
  [10/16] TAMBUSAI: 3,131 ha post-2020
  [11/16] SUBUR ARUM MAKMUR II: 159 ha post-2020
  [12/16] LIMPAH SEJAHTERA: 1,113 ha post-2020
  [13/16] PERDANA INTI SAWIT PERKASA 2: 513 ha post-2020
  [14/16] KETAPANG AGRO LESTARI: 1,112 ha post-2020
  [15/16] UMEKA SARI PRATAMA: 2,609 ha post-2020
  [16/16] SURYA DUMAI AGRINDO MILL: 1,432 ha post-2020

Saved 290 mills across 11 companies

### Check mill counts first

Confirm each company matches enough mills across both columns before running the full loop. Fix any keyword that comes back far too low.

In [19]:
# --- Verify mill counts across BOTH columns before trusting the master table ---
# Run this after defining COMPANIES. Any company far below its known mill count
# has a keyword problem and must be fixed before its forest-loss figure is used.

for _name, _kw in COMPANIES.items():
    _g = uml[group_col].str.contains(_kw, case=False, na=False, regex=True).sum()
    _p = uml["Parent Company"].str.contains(_kw, case=False, na=False, regex=True).sum()
    _both = (
        uml[group_col].str.contains(_kw, case=False, na=False, regex=True)
        | uml["Parent Company"].str.contains(_kw, case=False, na=False, regex=True)
    ).sum()
    print(f"{_name:16s} group={_g:3d}  parent={_p:3d}  combined={_both:3d}")

wilmar           group= 45  parent=  1  combined= 45
gar              group= 48  parent=  6  combined= 50
sdguthrie        group=  2  parent= 40  combined= 42
musimmas         group= 17  parent=  4  combined= 19
ioi              group= 15  parent= 10  combined= 15
klk              group= 29  parent= 10  combined= 30
bumitama         group= 14  parent=  3  combined= 15
astraagro        group= 33  parent=  2  combined= 34
genting          group= 14  parent= 10  combined= 15
sipef            group= 11  parent=  2  combined= 11
firstresources   group= 15  parent=  1  combined= 16

## Pre-meeting diagnostics

Two checks the supervisor is likely to probe.

In [20]:
# --- Pre-meeting diagnostics ---

# 1. Did any company return zero mills? Those numbers are not usable.
print("=== MILL COUNTS ===")
for _c in COMPANIES:
    _n = len(mills_master[mills_master["company"] == _c])
    _flag = "   <-- ZERO, keyword needs fixing" if _n == 0 else ""
    print(f"  {_c:16s} {_n:3d} mills{_flag}")

# 2. Do any Wilmar catchments overlap? (open limitation - double counting)
from itertools import combinations
import math

_w = mills_master[mills_master["company"] == "wilmar"]
_close = sum(
    1 for (_, a), (_, b) in combinations(_w.iterrows(), 2)
    if math.dist((a["latitude"], a["longitude"]), (b["latitude"], b["longitude"])) * 111 < 20
)
print(f"\n=== OVERLAP ===")
print(f"Wilmar mill pairs closer than 20 km: {_close}")
print("(each such pair shares catchment area, so some hectares are counted twice)")

=== MILL COUNTS ===
  wilmar            45 mills
  gar               50 mills
  sdguthrie         42 mills
  musimmas          18 mills
  ioi               15 mills
  klk               30 mills
  bumitama          14 mills
  astraagro         34 mills
  genting           15 mills
  sipef             11 mills
  firstresources    16 mills

=== OVERLAP ===
Wilmar mill pairs closer than 20 km: 19
(each such pair shares catchment area, so some hectares are counted twice)

## Single-mill detail

Year-by-year breakdown and the EUDR before/after split.

In [21]:
# --- Year-by-year loss for one mill (Wilmar Sabahmas, Sabah) ---

def loss_by_year(lon, lat, buffer_m=10000):
    region = ee.Geometry.Point([lon, lat]).buffer(buffer_m)
    out = {}
    for yr in range(21, 26):
        img = hansen.select("lossyear").eq(yr).multiply(pixel_ha)
        v = img.reduceRegion(ee.Reducer.sum(), region, 30, maxPixels=1e10).getInfo()
        out[2000 + yr] = round(v.get("lossyear") or 0)
    return out


def before_after(lon, lat, buffer_m=10000):
    region = ee.Geometry.Point([lon, lat]).buffer(buffer_m)
    _pre = hansen.select("lossyear").gte(1).And(hansen.select("lossyear").lte(20))
    _post = hansen.select("lossyear").gte(21)
    b = _pre.multiply(pixel_ha).reduceRegion(ee.Reducer.sum(), region, 30, maxPixels=1e10).getInfo()
    a = _post.multiply(pixel_ha).reduceRegion(ee.Reducer.sum(), region, 30, maxPixels=1e10).getInfo()
    return round(b.get("lossyear") or 0), round(a.get("lossyear") or 0)


_lon, _lat = 118.405246, 5.179162

print("Year-by-year loss (ha):")
for _y, _v in loss_by_year(_lon, _lat).items():
    print(f"  {_y}: {_v:,}")

_pre_ha, _post_ha = before_after(_lon, _lat)
print(f"\nEUDR split - 2001-2020: {_pre_ha:,} ha  |  2021-2025: {_post_ha:,} ha")

Year-by-year loss (ha):
  2021: 2,025
  2022: 589
  2023: 1,438
  2024: 1,372
  2025: 1,251

EUDR split - 2001-2020: 16,488 ha  |  2021-2025: 6,675 ha

## Master table

This is the CSV every number in the thesis must trace back to.

In [22]:
master = (
    mills_master
    .groupby("company", as_index=False)
    .agg(
        n_mills=("mill_name", "count"),
        forest_2000_ha=("forest_2000_ha", "sum"),
        loss_total_ha=("loss_total_ha", "sum"),
        loss_post2020_ha=("loss_post2020_ha", "sum"),
    ))
master["loss_pct_of_forest"] = (
    master["loss_post2020_ha"] / master["forest_2000_ha"] * 100).round(2)

# Normalises for company size — answers "is SD Guthrie top only because it has more mills?"
master["ha_per_mill"] = (master["loss_post2020_ha"] / master["n_mills"]).round(0)
master = master.sort_values("loss_post2020_ha", ascending=False).reset_index(drop=True)
master.to_csv("data/mills/master_forest_loss.csv", index=False)
master

,company,n_mills,forest_2000_ha,loss_total_ha,loss_post2020_ha,loss_pct_of_forest,ha_per_mill
0,gar,50,1.234269e+06,792970.995367,171236.168128,13.87,3425.0
1,sdguthrie,42,9.863202e+05,700217.038743,142131.279201,14.41,3384.0
2,wilmar,45,1.119815e+06,711440.929911,127605.651214,11.40,2836.0
3,klk,30,7.571609e+05,502073.696143,92208.918345,12.18,3074.0
4,astraagro,34,8.103222e+05,507344.985693,87198.086458,10.76,2565.0
5,ioi,15,3.906211e+05,292261.771873,74385.364496,19.04,4959.0
6,musimmas,18,4.635893e+05,301860.767177,53059.552603,11.45,2948.0
7,genting,15,3.821293e+05,243363.718735,44362.418926,11.61,2957.0
8,firstresources,16,3.897264e+05,267096.286626,40090.269846,10.29,2506.0
9,bumitama,14,3.529216e+05,237175.975455,30549.328832,8.66,2182.0
10,sipef,11,2.624088e+05,145321.152352,27340.872005,10.42,2486.0

## Map visualization (SD Guthrie example)
Interactive forest cover/loss map, `mill_coords` currently holds SD Guthrie mills. Rerun `get_company_mills(uml, keyword, name)` first to visualize another company.

In [23]:
gfc_map = ee.Image("UMD/hansen/global_forest_change_2025_v1_13")

# Ek picture banao: hara = jungle 2000 mein, laal = 2020 ke baad kata
image = gfc_map.select("treecover2000").gt(30).multiply(1).add(
        gfc_map.select("lossyear").gte(21).multiply(2))

# Sab mills ke GPS coordinates ek interactive map par dikhao
center_lat = mill_coords["latitude"].mean()
center_lon = mill_coords["longitude"].mean()

mills_map = folium.Map(location=[center_lat, center_lon], zoom_start=8)
folium.TileLayer(
    tiles="https://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z}",
    attr="Google Satellite",
    name="Google Satellite",
    overlay=False,
).add_to(mills_map)

map_id_dict = image.getMapId(
    {"min": 0, "max": 3, "palette": ["white", "green", "green", "red"]}
)
folium.raster_layers.TileLayer(
    tiles=map_id_dict["tile_fetcher"].url_format,
    attr="Google Earth Engine",
    name="Forest cover / loss",
    overlay=True,
    control=True,
).add_to(mills_map)

for _, _row in mill_coords.iterrows():
    folium.Marker(
        location=[_row["latitude"], _row["longitude"]],
        popup=f"{_row['Mill Name']} ({_row['latitude']}, {_row['longitude']})",
    ).add_to(mills_map)

folium.LayerControl().add_to(mills_map)
mills_map

## Sensitivity check (Week 2 task)

Recompute at 5 km and 15 km buffers. If the company ranking holds, that is a
robustness finding worth a paragraph in Results. If it shifts, that is a
limitation worth a paragraph. Either outcome is useful — run it and report it.

In [24]:
# Sensitivity: does the ranking survive a different buffer radius?
# Start with 2-3 companies to gauge how long the full run would take.

def sensitivity_check(uml_df, companies, radii=(5000, 10000, 15000)):
    out = []
    for _name, _keyword in companies.items():
        for _r in radii:
            _df = company_forest_loss(uml_df, _keyword, f"{_name}_{_r//1000}km", buffer_m=_r)
            out.append({
                "company": _name,
                "buffer_km": _r // 1000,
                "loss_post2020_ha": _df["loss_post2020_ha"].sum(),
            })
    return pd.DataFrame(out)

# subset = {k: COMPANIES[k] for k in ["wilmar", "gar", "sdguthrie"]}
# sens = sensitivity_check(uml, subset)
# sens.pivot(index="company", columns="buffer_km", values="loss_post2020_ha")

In [25]:
import pandas as pd
import os

os.makedirs("data", exist_ok=True)

COMPANIES = {
    "wilmar":         "WILMAR",
    "gar":            "GOLDEN AGRI|SINAR MAS",
    "sdguthrie":      "SIME DARBY",
    "musimmas":       "MUSIM MAS",
    "ioi":            "IOI CORPORATION|IOI GROUP",
    "klk":            "KUALA LUMPUR KEPONG|KLK",
    "bumitama":       "BUMITAMA",
    "astraagro":      "ASTRA AGRO|ASTRA",
    "genting":        "GENTING",
    "sipef":          "SIPEF",
    "firstresources": "FIRST RESOURCES",
    "apical":         "APICAL",
}

all_mills = []

for company, keyword in COMPANIES.items():
    mask = (
        uml[group_col].str.contains(keyword, case=False, na=False, regex=True) |
        uml["Parent Company"].str.contains(keyword, case=False, na=False, regex=True)
    )
    mills = uml[mask].drop_duplicates(subset=["Mill Name", "GPS coordinates"]).copy()

    # Safe coordinate parsing
    def parse_coord(series, idx):
        try:
            parts = series.str.split(",", expand=True)
            if idx in parts.columns:
                return pd.to_numeric(parts[idx].str.strip(), errors="coerce")
        except:
            pass
        return pd.Series([None]*len(series), index=series.index)

    mills["latitude"]  = parse_coord(mills["GPS coordinates"], 0)
    mills["longitude"] = parse_coord(mills["GPS coordinates"], 1)
    mills = mills.dropna(subset=["latitude", "longitude"])

    mills["company"] = company
    all_mills.append(mills[[
        "company", "Mill Name", group_col, "Parent Company",
        "Country", "latitude", "longitude", "RSPO Status"
    ]])

    print(f"{company:16s} {len(mills):3d} mills")

final = pd.concat(all_mills, ignore_index=True)
final.columns = ["company", "mill_name", "group_name", "parent_company",
                 "country", "latitude", "longitude", "rspo_status"]

final.to_csv("data/all_company_mills.csv", index=False)

print(f"\nTotal mills: {len(final)}")
print("Saved!")
final

wilmar            45 mills
gar               50 mills
sdguthrie         41 mills
musimmas          18 mills
ioi               15 mills
klk               30 mills
bumitama          14 mills
astraagro         34 mills
genting           15 mills
sipef             11 mills
firstresources    16 mills
apical             0 mills

Total mills: 289
Saved!

,company,mill_name,group_name,parent_company,country,latitude,longitude,rspo_status
0,wilmar,SABAHMAS,WILMAR GROUP,SABAHMAS PLANTATION SDN BHD,Malaysia,5.179162,118.405246,RSPO Certified
1,wilmar,SAREMAS 1,WILMAR GROUP,SAREMAS SDN BHD,Malaysia,3.524921,113.744412,RSPO Certified
2,wilmar,SAREMAS 2,WILMAR GROUP,SAREMAS SDN BHD,Malaysia,3.450453,113.765561,RSPO Certified
3,wilmar,TERUSAN,WILMAR GROUP,SAPI PLANTATION SDN BHD,Malaysia,5.831514,117.340459,RSPO Certified
4,wilmar,SAPI,WILMAR GROUP,SAPI PLANTATION SDN BHD,Malaysia,5.733519,117.387404,RSPO Certified
...,...,...,...,...,...,...,...,...
284,firstresources,LIMPAH SEJAHTERA,FIRST RESOURCES,LIMPAH SEJAHTERA,Indonesia,-1.716225,110.354369,Not RSPO Certified
285,firstresources,PERDANA INTI SAWIT PERKASA 2,FIRST RESOURCES,PERDANA INTISAWIT PERKASA,Indonesia,1.167333,100.704778,Not RSPO Certified
286,firstresources,KETAPANG AGRO LESTARI,FIRST RESOURCES,KETAPANG AGRO LESTARI,Indonesia,-0.875633,115.891653,Not RSPO Certified
287,firstresources,UMEKA SARI PRATAMA,FIRST RESOURCES,UMEKAH SARI PRATAMA,Indonesia,-2.1238,110.9809,Not RSPO Certified
288,firstresources,SURYA DUMAI AGRINDO MILL,UNKNOWN,FIRST RESOURCES,Indonesia,1.351417,102.067389,Not RSPO Certified

In [26]:
import pandas as pd
mills_df = pd.read_csv("data/all_company_mills.csv")
gar = mills_df[mills_df["company"] == "gar"][["mill_name", "latitude", "longitude"]].dropna()

for _, row in gar.iterrows():
    print(f'  {{name:"{row["mill_name"]}", lon:{row["longitude"]:.6f}, lat:{row["latitude"]:.6f}}},')

  {name:"UJUNG TANJUNG", lon:101.260750, lat:0.969733},
  {name:"LIBO", lon:101.206389, lat:0.928611},
  {name:"SAM-SAM", lon:101.300200, lat:0.937500},
  {name:"SEKIJANG", lon:101.044283, lat:0.833933},
  {name:"NAGA SAKTI", lon:101.049567, lat:0.782700},
  {name:"RAMARAMA", lon:101.076381, lat:0.533494},
  {name:"BUMI PALMA", lon:102.983333, lat:-0.598056},
  {name:"INDRA SAKTI", lon:102.305851, lat:-0.569200},
  {name:"PADANG HALABAN", lon:99.839444, lat:2.319167},
  {name:"LANGGA PAYUNG PALM OIL MILL", lon:99.886944, lat:1.654444},
  {name:"BATU AMPAR", lon:116.021900, lat:-3.198100},
  {name:"TANAH LAUR", lon:115.283056, lat:-3.790278},
  {name:"HANAU", lon:112.109694, lat:-2.360861},
  {name:"SUNGAI RUNGAU", lon:112.334000, lat:-2.320600},
  {name:"SEMILAR", lon:112.340417, lat:-2.248111},
  {name:"SUNGAI BUAYA", lon:105.438839, lat:-4.128611},
  {name:"SUNGAI MERAH", lon:105.588769, lat:-4.218444},
  {name:"JELATANG", lon:102.485833, lat:-2.072222},
  {name:"LANGLING", lon:102.374444, lat:-2.100833},
  {name:"MASKAPAI PERKEBUAN LEIDONG WEST", lon:105.476389, lat:-1.901389},
  {name:"TANJUNG KEMBIRI", lon:107.770416, lat:-3.032487},
  {name:"BUMI SAWIT", lon:104.344300, lat:-3.525700},
  {name:"PANGKALAN PANJI", lon:104.466511, lat:-2.948531},
  {name:"MUARA KANDIS", lon:103.177500, lat:-2.900278},
  {name:"PEKAWAI", lon:110.458915, lat:-1.521222},
  {name:"KENANGA PALM OIL MILL", lon:110.515800, lat:-2.140400},
  {name:"SUNGAI BENGKAL", lon:102.610000, lat:-1.590556},
  {name:"BUKIT PERAK", lon:105.550904, lat:-1.820147},
  {name:"MUARA WAHAU", lon:117.023161, lat:1.111161},
  {name:"JAK LUAY", lon:116.915000, lat:0.950833},
  {name:"PT BINASAWIT ABADI PRATAMA - PERDANA MILL", lon:112.359586, lat:-2.422506},
  {name:"BATU KAPUR", lon:116.047451, lat:-2.942661},
  {name:"BELIAN", lon:111.845392, lat:0.487029},
  {name:"PERSADA GRAHA MANDIRI", lon:111.730713, lat:0.400721},
  {name:"SUNGAI KIKIM", lon:103.219098, lat:-3.633013},
  {name:"PELAKAR", lon:102.642222, lat:-2.185278},
  {name:"SENAKIN", lon:116.186301, lat:-2.807667},
  {name:"SUNGAI KUPANG", lon:116.015417, lat:-3.053367},
  {name:"KUAYAN", lon:112.370324, lat:-1.970503},
  {name:"TANGAR", lon:112.299345, lat:-2.243602},
  {name:"KAPUASINDO PALM INDUSTRY", lon:111.879215, lat:1.019664},
  {name:"KASUARI", lon:140.029917, lat:-2.973111},
  {name:"SUNGAI MAGALAU", lon:116.171400, lat:-2.785260},
  {name:"JALEMO", lon:113.502200, lat:-1.348200},
  {name:"SAWITA", lon:116.140667, lat:-2.546639},
  {name:"SAKO", lon:112.238700, lat:-2.035600},
  {name:"SUNGAI AIR JERNIH", lon:102.801493, lat:-2.086512},
  {name:"RANTAU PANJANG", lon:116.828096, lat:0.970450},
  {name:"GUNUNG KOMBENG", lon:117.021880, lat:1.112055},
  {name:"BANGUNG NUSA MANDIRI KENARI", lon:110.920840, lat:-2.165160},

In [29]:
import pandas as pd
import json

master = pd.read_csv("data/mills/master_forest_loss.csv")

# Company name mapping — exact names
name_map = {
    "gar": "GAR",
    "sdguthrie": "SD Guthrie",
    "wilmar": "Wilmar",
    "klk": "KLK",
    "astraagro": "Astra Agro",
    "ioi": "IOI",
    "musimmas": "Musim Mas",
    "genting": "Genting",
    "firstresources": "First Resources",
    "bumitama": "Bumitama",
    "sipef": "SIPEF",
}

js_rows = []
for _, r in master.iterrows():
    company_key = r["company"].lower().replace(" ", "")
    js_rows.append({
        "company": name_map.get(r["company"], r["company"].title()),
        "n_mills": int(r["n_mills"]),
        "forest_2000": int(r["forest_2000_ha"]),
        "loss_total": int(r["loss_total_ha"]),
        "loss_post2020": int(r["loss_post2020_ha"]),
        "pct": round(float(r["loss_pct_of_forest"]), 2),
        "ha_per_mill": int(r["ha_per_mill"])
    })

js_output = "const data = " + json.dumps(js_rows, indent=2) + ";"

with open("data/data_array.js", "w") as f:
    f.write(js_output)

# Verify
print("Companies in JS array:")
for row in js_rows:
    print(f"  {row['company']:15s} | mills:{row['n_mills']:3d} | post2020:{row['loss_post2020']:,} ha | {row['pct']}%")

Companies in JS array:
  GAR             | mills: 50 | post2020:171,236 ha | 13.87%
  SD Guthrie      | mills: 42 | post2020:142,131 ha | 14.41%
  Wilmar          | mills: 45 | post2020:127,605 ha | 11.4%
  KLK             | mills: 30 | post2020:92,208 ha | 12.18%
  Astra Agro      | mills: 34 | post2020:87,198 ha | 10.76%
  IOI             | mills: 15 | post2020:74,385 ha | 19.04%
  Musim Mas       | mills: 18 | post2020:53,059 ha | 11.45%
  Genting         | mills: 15 | post2020:44,362 ha | 11.61%
  First Resources | mills: 16 | post2020:40,090 ha | 10.29%
  Bumitama        | mills: 14 | post2020:30,549 ha | 8.66%
  SIPEF           | mills: 11 | post2020:27,340 ha | 10.42%